name: Run CI
on: [push]
jobs:
  Run-All-Tests:
    name: "Run All Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: Ian Malcolm
          commit_user_email: ian@example.com
          commit_author: Ian Malcolm <ian@example.com>